### ISSUE TITLE
JSON parser allows invalid strings

### ISSUE THREAD

**Issue by jburse** [sasagawa888/opl#10]
I made the following test:

![image](https://user-images.githubusercontent.com/5411487/52217423-afbc3d00-2898-11e9-9c89-d03efbdae261.png)

**Comment by jburse** [comment]
But I don't find any syntax for that here:

    http://json.org/

Also SWI-Prolog doesn't accept it:

![image](https://user-images.githubusercontent.com/5411487/52217470-c9f61b00-2898-11e9-9257-b89bd4889e68.png)

**Comment by sasagawa888** [comment]
Dropped JSON support.
