### ISSUE TITLE
unnecessary parenthesis during unparse

### ISSUE THREAD

**Issue by jburse** [sasagawa888/opl#11]
Hi Ken,

I made a simple test:

![image](https://user-images.githubusercontent.com/5411487/52303849-64398a00-2991-11e9-9464-d65238191fc4.png)

**Comment by jburse** [comment]
The expected result is simpler:

![image](https://user-images.githubusercontent.com/5411487/52303862-74516980-2991-11e9-8b19-10a0a175e6c2.png)

**Comment by jburse** [comment]
You could analyze the problem, if your write_term had priority write option.
The behaviour is usually as follows:

![image](https://user-images.githubusercontent.com/5411487/52304373-eaa29b80-2992-11e9-900c-12035a0c2b45.png)

**Comment by jburse** [comment]
So basically for an yfx operator, the left hand side is called during 
unparsing with the same level, as the operator. The level is only 

decremented for an xfx operator. I think the mode (yfx,xfx) is
correctly stored, but the unparser has somewhere an error:

![image](https://user-images.githubusercontent.com/5411487/52304495-2b021980-2993-11e9-8ff3-283b81b2a9e5.png)

But the non-decrement for yfx is documented here:

![unbenannt](https://user-images.githubusercontent.com/5411487/52304632-79171d00-2993-11e9-89eb-658ebfab0669.PNG)


http://tau-prolog.org/files/doc/grammar-specification.pdf

**Comment by sasagawa888** [comment]
Fixed.
?- X = 1+2+3.
X = 1+2+3

Thank you.

**Comment by jburse** [comment]
Ok, I will do some regression testing when .exe is out, but closing the issue already now.
