### ISSUE TITLE
missing parenthesis in answer substitution

### ISSUE THREAD

**Issue by jburse** [sasagawa888/opl#12]
Hi Ken,

I made a little test:

![image](https://user-images.githubusercontent.com/5411487/52303979-d9a55a80-2991-11e9-9722-fb5e6811c45c.png)

**Comment by jburse** [comment]
But in this case parenthesis are expected:

![image](https://user-images.githubusercontent.com/5411487/52304014-ea55d080-2991-11e9-9402-378c6d46aff1.png)

**Comment by jburse** [comment]
I solve the Prolog in that I wrote the output of answer substitution itself in Prolog.
And I am using this to write them:

```
sys_show_name_or_eq(X = T, M) :- !,
   sys_quoted_var(X, Q),
   write(Q),
   write(' = '),
   write_term(T, [priority(699),quoted(true),variable_names(M)]).
```
https://github.com/jburse/jekejeke-devel/blob/master/jekrun/headless/jekpro/reference/runtime/session.p#L205

**Comment by jburse** [comment]
I don't find such a write option in O-Prolog:

![image](https://user-images.githubusercontent.com/5411487/52304134-415ba580-2992-11e9-85c5-e187ca559bd0.png)

**Comment by jburse** [comment]
You don't find this option in ISO 7.10.4 Write-options list.
But it can also be useful for other stuff. SWI-Prolog does also support it:

![image](https://user-images.githubusercontent.com/5411487/52304234-90a1d600-2992-11e9-9e99-ff494a37bcc5.png)

**Comment by sasagawa888** [comment]
FIxed.
?- X = (Y=Z).
X = (Y=Z)

Thank you.

**Comment by jburse** [comment]
Ok, I will do some regression testing when .exe is out, but closing the issue already now.
