### ISSUE TITLE
JSON parser does not accept all numbers

### ISSUE THREAD

**Issue by jburse** [sasagawa888/opl#13]
Hi Ken,

I did a little test, this is not a urgent problem, only want to notify you:

![image](https://user-images.githubusercontent.com/5411487/52357304-38241480-2a36-11e9-9d6b-d30c81dfab93.png)

**Comment by jburse** [comment]
But from the json.org syntax, this should be allowed.

SWI-Prolog does also show a different behaviour:

![image](https://user-images.githubusercontent.com/5411487/52357369-5853d380-2a36-11e9-9667-f5b74965a14e.png)

I took the test case from here:
https://github.com/SWI-Prolog/packages-http/blob/master/test_json.pl

**Comment by sasagawa888** [comment]
Dropped JSON support.
