### ISSUE TITLE
Feature request O-Prolog should be implemented as objects

### ISSUE THREAD

**Issue by jburse** [sasagawa888/opl#16]
Hi Ken,

I find `extern token stok;` in opl.h.
With this it is impossible to have multi-threading.

Imagine one thread does read/1 and another thread 
does read/1 as well.

To go multi-threading you need to objectify everything.

Bye

**Comment by jburse** [comment]
Will this be solved with Elxlog?

**Comment by sasagawa888** [comment]
There is no plan.
