### ISSUE TITLE
top-level hangs for cyclic terms

### ISSUE THREAD

**Issue by jburse** [sasagawa888/opl#20]
Hi,

I get:

```
   O-Prolog Ver 1.70 (Chisato)
   | ?- X = [1|X], Y = [1|Y].
   %%% crashes after some times %%%
```

Bye

**Comment by jburse** [comment]
On the other hand GNU Prolog does the following:

![image](https://user-images.githubusercontent.com/5411487/53304702-b24afa80-3878-11e9-86fb-44213e29ebd5.png)

**Comment by sasagawa888** [comment]
It is not in the ISO standard.
