### ISSUE TITLE
Openbsd port

### ISSUE THREAD

**Issue by alexshendi** [sasagawa888/opl#21]
I ported the code to OpenBSD. How do I proceed? Should I send you a diff or should I send a pull request?

Best Regards, 

Alexander

**Comment by sasagawa888** [comment]
Thank you very much.
Please send a pull request.
I will merge.
I am new to GitHub. It may take a little time.

Kenichi Sasagawa

**Comment by sasagawa888** [comment]
Merged. Thank you.

**Comment by sasagawa888** [comment]
Dear Alexander.

I made a bug fix for OPL.
The previous OPL did not work with gcc 7.3 or later.
I improved and confirmed the operation with Linux such as Ubuntu.
However, I do not have OpenBSD environment.
I'd appreciate it if you could test new OPL.
https://github.com/sasagawa888/opl

Kenichi Sasagawa
