### ISSUE TITLE
sort/2 does not remove duplicates

### ISSUE THREAD

**Issue by jburse** [sasagawa888/opl#25]
Hi Ken,

The ISO core standard requires that sort/2 will remove 
duplicates. I made a small check. It seems that OPL does
not yet implement duplicate removal:

![image](https://user-images.githubusercontent.com/5411487/53914884-f4392500-405e-11e9-8e50-c6302938c207.png)

**Comment by jburse** [comment]
Here you see the expected result in GNU Prolog:

![image](https://user-images.githubusercontent.com/5411487/53914936-0e730300-405f-11e9-8995-b789cd23247b.png)

**Comment by sasagawa888** [comment]
Fixed. Thank you.
O-Prolog Ver 1.70 (Chisato)
| ?- sort([A,B,A],X).
X = [A,B]
yes
| ?- sort([1,2,1],X).
X = [1,2]
yes
|
