### ISSUE TITLE
keysort/2 does not sort variables

### ISSUE THREAD

**Issue by jburse** [sasagawa888/opl#26]
Hi Ken

The ISO core standard requires that keysort/2 can also sort
variables, when they appear as keys. Similarly like the predicates
(@<)/2, (@>)/2, (@>=)/2 and (@=<)/2 should be able to compare variables.

It seems not to work:

![image](https://user-images.githubusercontent.com/5411487/53915076-7aee0200-405f-11e9-9b11-1f5b5facbb14.png)

**Comment by jburse** [comment]
Here you see the expected result in GNU-Prolog;

![image](https://user-images.githubusercontent.com/5411487/53915124-9e18b180-405f-11e9-8b4d-f271b846a1dd.png)

**Comment by sasagawa888** [comment]
Fixed. Thank you.

O-Prolog Ver 1.70 (Chisato)
| ?- keysort([A-1,B-2,A-3],X).
X = [A-1,A-3,B-2]
yes
| ?- keysort([foo-1,bar-2,foo-3],X).
X = [bar-2,foo-1,foo-3]
yes
|
