### ISSUE TITLE
superflous parenthesis during term writing

### ISSUE THREAD

**Issue by jburse** [sasagawa888/opl#30]
Hi Ken,

Was playing around with operators. It seems that terrm 
writing puts a little bit too many parenthesis (-a)+b:

![image](https://user-images.githubusercontent.com/5411487/54242776-21397c00-4526-11e9-9672-e9fd5311e048.png)

**Comment by jburse** [comment]
Here is the expected result from GNU Prolog:

![image](https://user-images.githubusercontent.com/5411487/54242794-36160f80-4526-11e9-9f7b-91b35aacf1eb.png)

**Comment by sasagawa888** [comment]
Fixed. Thank you.

O-Prolog Ver 1.71 (Chisato)
| ?- X = -a+b,write_canonical(X),nl.
+(-(a),b)
X = -a+b
yes
