### ISSUE TITLE
tarai needs a cut

### ISSUE THREAD

**Issue by jburse** [sasagawa888/opl#32]
Hi,

Was playing around with your tarai function. Its part of your distribution 
in the file tarai.pl. The Prolog version needs a cut, otherwise it will create 
choice points, and not be able to run. 

Here without cut SWI-Prolog, the current original tarai.pl:

![image](https://user-images.githubusercontent.com/5411487/54528340-03807280-497d-11e9-8cc9-decf5d49d950.png)

Here without cut Jekejeke Prolog, the current original tarai.pl:

![image](https://user-images.githubusercontent.com/5411487/54528355-109d6180-497d-11e9-97c0-44bff5d2e50b.png)

**Comment by jburse** [comment]
There is also another error, that Z is a singleton variable. But placing
a cut makes the predicate "deterministic", and the Prolog interpreter
doesn't need to place choice points, 

respectively the cut will remove choice points, and therefore 
the example can be executed:

Here with cut SWI-Prolog, the file tarai.pl modified:

![image](https://user-images.githubusercontent.com/5411487/54528446-4d695880-497d-11e9-9e7b-2db4b92244d4.png)

Here with cut Jekejeke Prolog, the file tarai.pl modified:

![image](https://user-images.githubusercontent.com/5411487/54528471-5bb77480-497d-11e9-855e-601e92aeedf6.png)

**Comment by jburse** [comment]
Does O-Prolog also remove choice points by the cut?

It seems that it doesn't execute:

![image](https://user-images.githubusercontent.com/5411487/54528557-a2a56a00-497d-11e9-85d6-d4a7b68fd193.png)

**Comment by jburse** [comment]
Among faster Prolog systems is ECLiPSe Prolog and YAP. 
ECLiPSe Prolog does have BigNums, but YAP doesn't have BigNums:

![image](https://user-images.githubusercontent.com/5411487/54531848-97a30780-4986-11e9-9886-921e52ce6eb1.png)

![image](https://user-images.githubusercontent.com/5411487/54531902-bdc8a780-4986-11e9-942d-d7be43de1638.png)

GNU Prolog hopelessly crashes for the example.

**Comment by jburse** [comment]
Hi Ken,

You could also test with these variants:

tarai_cut(X,Y,_,Y) :- X=<Y, !.
tarai_cut(X,Y,Z,R) :-
    X1 is X-1, tarai_cut(X1,Y,Z,Rx),
    Y1 is Y-1, tarai_cut(Y1,Z,X,Ry),
    Z1 is Z-1, tarai_cut(Z1,X,Y,Rz),
    tarai_cut(Rx,Ry,Rz,R).

tarai_or(X,Y,Z,R) :- X=<Y, !, R=Y;
    X1 is X-1, tarai_or(X1,Y,Z,Rx),
    Y1 is Y-1, tarai_or(Y1,Z,X,Ry),
    Z1 is Z-1, tarai_or(Z1,X,Y,Rz),
    tarai_or(Rx,Ry,Rz,R).

tarai_if(X,Y,Z,R) :- X=<Y -> R=Y;
    X1 is X-1, tarai_if(X1,Y,Z,Rx),
    Y1 is Y-1, tarai_if(Y1,Z,X,Ry),
    Z1 is Z-1, tarai_if(Z1,X,Y,Rz),
tarai_if(Rx,Ry,Rz,R).

**Comment by jburse** [comment]
Actually the if-then-else version should run fastest as in YAP Prolog:

```
   YAP 6.3.3 (i686-mingw32): Sun Jan 20 18:27:56 GMTST 2013

   ?- time(tarai_cut(12,6,0,X)).
   % 0.687 CPU in 0.690 seconds ( 99% CPU)
   X = 12

   ?- time(tarai_or(12,6,0,X)).
   0.734 CPU in 0.735 seconds ( 99% CPU)
   X = 12

   ?- time(tarai_if(12,6,0,X)).
   % 0.515 CPU in 0.516 seconds ( 99% CPU)
   X = 12
```

**Comment by jburse** [comment]
Hi Ken,

Scryer Prolog cant do tarai neither, I had to kill it after 1.5 minutes:

![image](https://user-images.githubusercontent.com/5411487/55419300-b9021700-5574-11e9-8a13-41a3874f06eb.png)

**Comment by sasagawa888** [comment]
It is not in the ISO standard.
