### ISSUE TITLE
disjunction is not executed

### ISSUE THREAD

**Issue by jburse** [sasagawa888/opl#33]
Hi Ken,

Was playing around with disjunction. Found a bug in O-Prolog. The
below query should give 4 answers. But O-Prolog only gives 3 answers:

![image](https://user-images.githubusercontent.com/5411487/55204715-56092c80-51d0-11e9-827d-b78afcc625ed.png)

The Prolog cut should only affect what is left of the cut, and not 
what is right of the cut. Therefore it should show 4 solutions.

**Comment by jburse** [comment]
You can cross check with GNU Prolog, it gives the following result:

![image](https://user-images.githubusercontent.com/5411487/55204783-8f419c80-51d0-11e9-936a-f54562e11295.png)

**Comment by sasagawa888** [comment]
Fixed.　Thank you.
O-Prolog Ver 1.70 (Chisato)
| ?- ((X=1;X=2),Y=6;Y=7,!,(X=3;X=4)).
X = 1
Y = 6;
X = 2
Y = 6;
X = 3
Y = 7;
X = 4
Y = 7;
no
