### ISSUE TITLE
feature request: dialect Prolog flag

### ISSUE THREAD

**Issue by jburse** [sasagawa888/opl#35]
Hi,

I was just checking, whether O-Prolog has a dialect flag. 
But it seems to be missing:

![image](https://user-images.githubusercontent.com/5411487/57878565-9709de80-781a-11e9-8faa-3a8d32b8d1e8.png)

Other Prolog systems have this flag, although it is not
mentioned in the ISO core standard:

![image](https://user-images.githubusercontent.com/5411487/57878599-aa1cae80-781a-11e9-8de8-d92d2c778b57.png)

How about providing a value for this flag?

**Comment by jburse** [comment]
I will provide this flag in upcoming release 1.3.7 of Jekejeke
Prolog. I made a test, it is quite wide spread among Prolog systems:


GNU   Prolog 1.4.5 (64 bits) | gprolog
-- | --
Version 7.0   #36 (x86_64_nt) | eclipse
SWI-Prolog   (threaded, 64 bits, version 8.1.5) | swi
YAP 6.3.3   (i686-mingw32) | yap
Jekejeke   Prolog 1.3.7 | jekejeke
Tau Prolog   0.2.65 beta | tau
Ciao   1.15-1781-g328b907 | ciao
JIProlog   4.1.6.1 | jiprolog
SICStus Prolog   (64-bit) VC15 4.5.1 | sicstus

**Comment by sasagawa888** [comment]
There is no plan.
