### ISSUE TITLE
unnesseary parenthesis during term write

### ISSUE THREAD

**Issue by jburse** [sasagawa888/opl#38]
Hi,

Just by accident I stepped over a little bug. I was 
inputing the following clause:

```
demo3 :- 1+2+3+4+(1+2+3+4+5+6+7+8+9+10+11+12+13+14+15+16+
         17+18+19+20+21+22+23+24+25+26+27+28+29+30)+6+7+8+
         9+10+11+12+(1+2+3+4+5+6+7+8+9+10+11+12+13+14+15+
         16+17+18+19+20+21+22+23+24+25+26+27+28+29+30)+14+
         15+16+17+18+19+20+21+22+23+24+25+26+27+28+29+30.
```

And expectation was that tonly the 2 parenthesis pairs are
shown during listing. But somehow this didn't work correctly.

Bye

**Comment by jburse** [comment]
I get the following result in OPL:

![image](https://user-images.githubusercontent.com/5411487/62416721-4bf4b000-b640-11e9-810a-2248821f2e22.png)

On the other hand the expected result would be:

![image](https://user-images.githubusercontent.com/5411487/62416730-6169da00-b640-11e9-9133-4ef4ed7a4544.png)

**Comment by jburse** [comment]
Probably related to:
https://github.com/sasagawa888/opl/issues/30

But this time its a binary operator.

**Comment by sasagawa888** [comment]
Fixed .

| ?- listing.
demo3 :-
    1+2+3+4+(1+2+3+4+5+6+7+8+9+10+11+12+13+14+15+16+17+18+19+20+21+22+23+24+25+26+27+28+29+30)+6+7+8+9+10+
11+12+(1+2+3+4+5+6+7+8+9+10+11+12+13+14+15+16+17+18+19+20+21+22+23+24+25+26+27+28+29+30)+14+15+16+17+18+19
+20+21+22+23+24+25+26+27+28+29+30.
yes
