### ISSUE TITLE
trampolin and last call optimization missing

### ISSUE THREAD

**Issue by jburse** [sasagawa888/opl#39]
Hi,

It seems your Prolog doesn't use a trampolin and last
call optimization. I cannot run this code indefinitely:

```
loop.
loop :- loop.
?- loop, fail.
```
I get the following error:

![image](https://user-images.githubusercontent.com/5411487/62429176-73647f00-b70b-11e9-9e01-1509e73cc50c.png)

**Comment by jburse** [comment]
On the other hand if I run the same in SWI-Prolog,
I get the following, I can run it hours and hours:

![image](https://user-images.githubusercontent.com/5411487/62429187-9e4ed300-b70b-11e9-8515-d4493076167e.png)

Also my system can do the same, I can run it hours and hours.
In my system there is even no special code for loops, its
only trampoilin and last call optimization:

![image](https://user-images.githubusercontent.com/5411487/62429213-0ef5ef80-b70c-11e9-8ee7-6628a4964b72.png)

**Comment by jburse** [comment]
He Ken,

Don't take me wrong, last call optimization and trampolin is no joke. Its at
the heart of Erlang family of languages, for concurrent programming, and
was also pioneered by Prolog. Here is an example of a pong process

which should run indefinitely:

I stopped the process by pressing CTRL-period.

**Comment by jburse** [comment]
You might lookup "perpetual processes" in
the logic programming classic by John W. Lloyd.
This is in chapter 4 of this book:

    © 1984 Foundations of Logic Programming
    https://www.springer.com/gp/book/9783642968266

**Comment by sasagawa888** [comment]
It is not in the ISO standard.
