### ISSUE TITLE
between/3 should run in constant space

### ISSUE THREAD

**Issue by jburse** [sasagawa888/opl#41]
Hi,

I tried whether between/3 runs in constant space or not.
It seems it doesn't run in constant space:

![image](https://user-images.githubusercontent.com/5411487/62615088-e7ba4080-b90c-11e9-957d-e40d37040d86.png)

**Comment by jburse** [comment]
Here you see that it runs in constant space in
another Prolog system:

![image](https://user-images.githubusercontent.com/5411487/62615272-41bb0600-b90d-11e9-8996-61e9b25fa60e.png)

There are different approaches to solve the problem.
One solution is to have a native implementation of
between/3. 

Another solution is to have it implemented in Prolog 
itself, and then your Prolog system needs this fixed:

**Comment by jburse** [comment]
A primitive ISO Prolog implementation, without
type checks and range checks etc.. reads as follows.
I am calling it inside/3 istead of between/3:

    inside(I,_,I).
    inside(I,J,K) :-
       I<J,
       L is I+1,
       inside(L,J,K).

**Comment by sasagawa888** [comment]
It is not in the ISO standard.
