### ISSUE TITLE
JSON cannot be embedded in script

### ISSUE THREAD

**Issue by jburse** [sasagawa888/opl#44]
Hi,

I am playing around with your JSON library. I am also doing some
improvements to my own JSON library. It seems that / is not escaped:

![image](https://user-images.githubusercontent.com/5411487/62859543-bfac5200-bcfd-11e9-9487-75a9ad80a048.png)

The expectation is that the slash / is escaped.

**Comment by jburse** [comment]
You can compare with SWI-Prolog:

![image](https://user-images.githubusercontent.com/5411487/62859585-dd79b700-bcfd-11e9-846e-431e4677b2db.png)

Also documentation in SWI-Prolog says the same:

> If a string is emitted, the sequence </ is emitted as <\/. This
>  is valid JSON syntax which ensures that JSON objects can be 
> safely embedded into an HTML <script> element.
https://www.swi-prolog.org/pldoc/man?predicate=json_write/2

**Comment by jburse** [comment]
But it seems that many web sites produce JSON in a way,
that you don't need to check "</", you can just always escape
"/" to be on the safe side. For example I find this here:

**Comment by sasagawa888** [comment]
Dropped JSON support.
