### ISSUE TITLE
clause indexing and/or choice point elimination missing

### ISSUE THREAD

**Issue by jburse** [sasagawa888/opl#45]
A prerequisite to last call optimization is choice point
elimination, which in turn profits from clause indexing.
The dependency is:

```
      +----------------------------------+ 
      | Clause Indexing                  | 
      +----------------------------------+ 
                      | 
                      v 
      +----------------------------------+ 
      | Choice Point Elimination         | Prof Takeuchi, TAO 
      +----------------------------------+ 
                      | 
                      v 
      +----------------------------------+ 
      | Last Call Optimization           | Prof Warren, WAM 
      +----------------------------------+ 
```

Clause indexing sharpens last call optimization, since it sharpens 
choice point elimination. Clause indexing can identify more clauses 
as Hinge clauses, see Prof Takeuchi, TAO, than without clause indexing.

But for last call optimization, you need to know the Hinge clauses. I
made a test. I think OPL leaves some choice points, but I am not
sure. Here it asks me again, whether I want to see more solutions:

```
O-Prolog Ver 1.70 (Chisato) 

?- reverse([1,2,3],X,[]). 
X = [3,2,1] ; 
true 
```

**Comment by jburse** [comment]
SWI-Prolog doesn't ask for more solutions, since like many Prolog
systems (GNU, SWI, YAP, Jekejeke, etc..) it can eliminate choice points
and it detects in the top-level, where no more choice point is there for

the query. If all choice points of the query have been eliminated, there
is no use in asking for more solutions, since anyway there cannot be more
solutions, there are no choice points. See also:

![Bildschirmfoto 2019-08-12 um 16 46 59](https://user-images.githubusercontent.com/5411487/62874063-d6b06b80-bd20-11e9-897f-1686dfcfed64.png)

You need to have clause indexing and choice point elimination in place,
before you can even begin with last call optimization.

**Comment by sasagawa888** [comment]
It is not in the ISO standard.
