### ISSUE TITLE
parser bug

### ISSUE THREAD

**Issue by sasagawa888** [sasagawa888/opl#9]
O-Prolog Ver 1.70 (Chisato)
| ?- X = 1 - -2.
Syntax error not one operand with no operator
| Syntax error not one operand with no operator
| ?- X = 1 - (-2).
Syntax error not one operand with no operator
| X = 1--2
yes
|

**Comment by sasagawa888** [comment]
Partialy fixed.
O-Prolog Ver 1.70 (Chisato)
| ?- X = 1-(-2).
X = 1--2
yes

**Comment by sasagawa888** [comment]
fixed.
O-Prolog Ver 1.70 (Chisato)
| ?- X = 1- -2.
X = 1--2
yes
|

**Comment by jburse** [comment]
He, since this is not my issue, I cannot close it. But if you think it is fixed, you should see somewhere a GitHub "Close Issue" button, and you can press the GitHub "Close Issue" button and the issue moves to the GitHub closed list.

**Comment by sasagawa888** [comment]
Thank you.
